# Generated by Django 2.2.6 on 2020-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200216_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='文件名称')),
                ('path', models.FileField(help_text='只能是 zip 文件', upload_to='upfile/', verbose_name='文件路径')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
